#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/l0gic/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
DISPLAY=:0.0 conky -c ~/.conkyrc -d
DISPLAY=:0.0 conky -c ~/.conkyrc2 -d
DISPLAY=:0.0 sh ~/.fehbg

DISPLAY=:0.1 conky -c ~/.conkyrc_tv -d
DISPLAY=:0.1 conky -c ~/.conkyrc2_tv -d
DISPLAY=:0.1 sh ~/.fehbg

xscreensaver -nosplash &

# Start DBUS session bus:
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
   eval $(dbus-launch --sh-syntax --exit-with-session)
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/l0gic/.fluxbox/log"
